### ISSUE TITLE
Keepalive?

### ISSUE THREAD

**Issue by frioux** [zostay/WebService-Bonusly#4]
This module uses Furl, and as far as I can tell Furl doesn't support Keepalive (at least it doesn't document it.)  The bonusly API is _crazy_ slow lately.  I suspect it would be worth using a different user agent to be able to use Keepalive.

Thoughts?

**Comment by zostay** [comment]
Probably. I'm not sure I like Furl. I tried it because it was the new hotness and less bloated than LWP, but I have not had a super-great experience with it. I have this issue and it deals with encoding badly too (i.e., it does not handle encoding), which annoys me.

**Comment by zostay** [comment]
Keep-alive is now turned on by default in the newly released 1.000 version.

**Comment by frioux** [comment]
Oh I'm so excited! I'm gonna give you bonus.ly in the morning and I bet a
dollar it takes half the time as normal

## 

sent from a rotary phone, pardon my brevity

**Comment by zostay** [comment]
I hope it works. I probably should have marked this as a dev release because I haven't actually tested it live against bonus.ly. I am a bad person. 

I have started to write automated tests to do that, so I hope to have them running on Travis-CI soon, but now it's night-night time.
