### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by frioux** [zostay/WebService-Bonusly#5]
https://metacpan.org/source/WebService::Bonusly::Service#L63

Sometimes you'll get a timeout or something from the bonusly API, and the json decoding fails.  Instead of getting an error like this:

```
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "Cannot connect to bo...") at /home/frew/.plenv/versions/5.22.0/lib/perl5/site_perl/5.22.0/JSON.pm line 171.
```

It would be great if Bonusly trapped the error and returned a proper object so I could either retry or at least make the error more clear.

**Comment by zostay** [comment]
The Bonus.ly API does not handle certain errors well. I'll see what I can do to make the unexpected-unexpected errors handier.
